---
title: "cross_validation"
author: "Qinting Shen"
date: "2023-11-14"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
```

```{r}
set.seed(1)
```


## Nonlinear data and CV
```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point()

```

Do the train / test split
```{r}
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df, train_df, by = "id") # return those in nonlin_df, but not in train_df

ggplot(train_df, aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```


quick visualization of the linear model

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

```{r}
train_df |> 
  add_predictions(linear_mod) |> 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")

train_df |> 
  add_predictions(smooth_mod) |> 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")

train_df |> 
  add_predictions(wiggly_mod) |> 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

compute root mean squared errors (RMSEs) for each model.

RMSEs on he training data can be misleading ...
```{r}
rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(smooth_mod, train_df)
```

RMSE on testing data gives a sense of out-of-sample prediction accuracy!
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(smooth_mod, test_df)
```


## Use modelr for CV

```{r}
cv_df = 
  crossv_mc(nonlin_df, 100) # why 100
```


```{r}
cv_df |> pull(train) |> nth(1) |> as_tibble() #? resample
```

```{r}
cv_df =
  cv_df |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

Apply each model to all training datasets, and evaluate on all testing datasets.

```{r}
cv_df = 
  cv_df |> 
  mutate( # 2 ways to use map
    linear_mod  = map(train, \(df) lm(y ~ x, data = df)),
    smooth_mod  = map(train, ~mgcv::gam(y ~ s(x), data = .x)),
    wiggly_mod  = map(train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))) |> 
  mutate( # map2_dbl: iterate over two arguments at a time
    rmse_linear = map2_dbl(linear_mod, test, \(mod, df) rmse(mod, df)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(wiggly_mod, test, ~rmse(model = .x, data = .y)))
```


```{r}
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```




